#!/usr/bin/env node
/*
 * Zero-dependency build: assembles loadable extension folders from src/.
 *
 *   node scripts/build.mjs            -> builds dist/chrome and dist/firefox
 *
 * Each target gets every shared asset plus the right manifest.json.
 * Run it after editing anything in src/.
 */
import { cp, mkdir, rm, readdir, copyFile, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "src");
const dist = join(root, "dist");

// Files in src/ that are build inputs, not shipped as-is.
const MANIFESTS = { chrome: "manifest.chrome.json", firefox: "manifest.firefox.json" };
const SKIP = new Set(Object.values(MANIFESTS));

async function copyShared(target) {
	const out = join(dist, target);
	await rm(out, { recursive: true, force: true });
	await mkdir(out, { recursive: true });

	for (const entry of await readdir(src, { withFileTypes: true })) {
		if (SKIP.has(entry.name)) continue;
		if (entry.name === "lib" && !existsSync(join(src, "lib", "."))) continue;
		const from = join(src, entry.name);
		const to = join(out, entry.name);
		if (entry.isDirectory()) {
			// skip empty dirs (e.g. an unused lib/)
			const inner = await readdir(from);
			if (inner.length === 0) continue;
			await cp(from, to, { recursive: true });
		} else {
			await copyFile(from, to);
		}
	}
	// drop in the target-specific manifest as manifest.json
	await copyFile(join(src, MANIFESTS[target]), join(out, "manifest.json"));
	return out;
}

async function version() {
	const m = JSON.parse(await readFile(join(src, MANIFESTS.chrome), "utf8"));
	return m.version;
}

const v = await version();
for (const target of Object.keys(MANIFESTS)) {
	const out = await copyShared(target);
	console.log(`✔ ${target.padEnd(8)} -> ${out}  (v${v})`);
}
await writeFile(join(dist, "README.txt"),
	"Generated by scripts/build.mjs — load the chrome/ or firefox/ folder as an unpacked extension.\n");
console.log("Done.");
